export enum ControllerEntity {
  CATEGORY = "category",
  CARTE = "carte",
  CUSTOMER = "customer",
  USER = "users",
  RECIPE = "recipe",
  CONFIG = "config",
  USER_GROUP = "userGroup",
  ROLE = "role",
  ORDER = "order",
  ORDER_ITEM = "orderItem",
  STOCK = "stock",
  PROMOTION = "promotion",
  NOTIFICATION = "notification",
}
